sudo: required
services:
    - docker
    
before_install:
    - docker build -t lototskyi/docker-react -f Dockerfile.dev .
    
script:
    - docker run lototskyi/docker-react npm run test -- --coverage